### ISSUE TITLE
[BUG] - Generation Error in V.2.10.0

### ISSUE THREAD

**Issue by kemotx90** [OpenAPITools/openapi-generator-cli#758] opened 2024-03-04 09:57 UTC
# 🐛 Bug Report:
The generation of file from this configuration has broken in V2.10.0 (but worked fine in V.2.9.0 or previous)

```json
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "7.2.0",
    "generators": {
      "my-application": {
        "generatorName": "typescript-angular",
        "output": "generated-sources/openapi",
        "inputSpec": "http://localhost:8080/***.yaml",
        "auth": "Authorization:*****",
        "typeMappings": {
          "DateTime": "Date"
        },
        "additionalProperties": {
          "supportsES6": true,
          "withInterfaces": true
        }
      }
    }
  }
}
```

When run from CLI
```shell
openapi-generator-cli generate --generator-key my-application
```

get this error
```log
[[my-application] http://localhost:8080/***.yaml] La sintassi del nome del file, della directory o del volume non � corretta.
[[my-application] http://localhost:8080/***.yaml] C:\...\jdk-11.0.18/bin/java" -jar "D:\...\node_modules\@openapitools\openapi-generator-cli\versions\7.2.0.jar" generate --input-spec="ht
tp://localhost:8080/***.yaml" --generator-name="typescript-angular" --output="generated-sources/openapi" --auth="Authorization:***" --type-mappings="DateTime=Date" --additional-properties="
supportsES6=true,withInterfaces=true exited with code 1
[brd] http://localhost:8080/***.yaml
  C:\***\jdk-11.0.18/bin/java" -jar "D:\***\node_modules\@openapitools\openapi-generator-cli\versions\7.2.0.jar" generate --input-spec="http://localhost:8080/***.yaml" --gener
ator-name="typescript-angular" --output="generated-sources/openapi" --auth="***" --type-mappings="DateTime=Date" --additional-properties="supportsES6=true,withInterfaces=true

Code generation failed

Process finished with exit code 1
```

If i'm rollback to 2.9.0 all work fine

**Comment by hassmal** [comment] 2024-03-05 05:04
Same problem here

**Comment by jase88** [comment] 2024-03-05 06:33
Seems to be Windows specific?

**Comment by hassmal** [comment] 2024-03-05 06:37
> Seems to be Windows specific?

maybe, I'm also on windows

**Comment by kemotx90** [comment] 2024-03-05 08:20
I'm on windows too

**Comment by zakupower** [comment] 2024-03-05 08:24
Same issue on Windows

**Comment by wing328** [comment] 2024-03-05 09:00
thanks for reporting the issue.

@mok-liee can you please take a look when you've time?

related PR: https://github.com/OpenAPITools/openapi-generator-cli/pull/756

**Comment by mbuxmann** [comment] 2024-03-05 14:59
Same here however on my Macbook it keeps looking for android package

Error: /bin/sh: /Applications/Android: No such file or directory

**Comment by mok-liee** [comment] 2024-03-05 15:04
i can understand the problem but unfortunately i can't reproduce it in my windows environment.
but i think that using `path.join` should solve the problem. sorry for that

**Comment by mok-liee** [comment] 2024-03-05 16:17
okay, i can reproduce it now. it seems to behave differently if you start the generation via the openapitools.json. i'll take a look at it.

**Comment by mok-liee** [comment] 2024-03-05 17:12
to pinpoint it a little bit, i think that `concurrently` doesn't like how the command is passed

**Comment by mok-liee** [comment] 2024-03-06 00:27
@wing328 I think without a windows build workflow it is difficult to determine whether it runs under windows.
except for one test, i have been able to recreate the build plan for windows.

branch:
https://github.com/mok-liee/openapi-generator-cli/tree/feature/add-windows-to-build
compare:
https://github.com/mok-liee/openapi-generator-cli/compare/patch-2...mok-liee:openapi-generator-cli:feature/add-windows-to-build

also i have added a `generate` test with `JAVA_HOME` (it was the default) and now without.

i need an understanding of the following test:
`npm run oa:generate && mkdir ./foo && cd ./foo && npm run oa:generate`

the last `npm run oa:generate`, is it correct that the `generate` command must find the `openapitools.json` in the parent folder?
if this is the case, i unfortunately cannot find where this logic is located. can you help me?

here you can see (i hope) my last build https://github.com/mok-liee/openapi-generator-cli/actions/runs/8164577233/job/22320124191

windows does not seem to look in the parent folder.

i think this could be the last step to get this thing running.

**Comment by mok-liee** [comment] 2024-03-06 01:55
i think i have it
https://github.com/OpenAPITools/openapi-generator-cli/blob/5d0e7c0fc1076ba783424c89bf61c9bff6f112ed/apps/generator-cli/src/app/services/config.service.ts#L10

`process.env.PWD` returns on Unix the parent directory and under Windows nothing
`process.env.INIT_CWD` returns on both the `foo` directory
`process.cwd()` returns on both the parent directory

fix is in 15ac43e63e31a39a654eee13693e3f1e4c535322 but because it is not enough there is another problem
https://github.com/mok-liee/openapi-generator-cli/actions/runs/8165673935/job/22323245537
i will continue the days

**Comment by wing328** [comment] 2024-03-06 05:32
thanks @mok-liee I'll revert the change for the time being.

**Comment by wing328** [comment] 2024-03-06 05:53
reverted, please install the latest release: https://github.com/OpenAPITools/openapi-generator-cli/releases/tag/v2.11.0

**Closed by wing328** 2024-03-06 05:53 UTC
Labels: bug
