### ISSUE TITLE
Version-Manager does not work with cygwin

### ISSUE THREAD

**Issue by amjmhs** [OpenAPITools/openapi-generator-cli#75] opened 2020-10-15 10:43 UTC
I just updated the openapi-generator-cli at our project to version 2.0.3 including the new version manager. I use windows with cygwin and the generated `openapitools.json` is not generated and located at the working-directory of the project.
I searched the system and found the file located under `C:\cygdrive\c\path\to\my\project` instead of `C:\path\to\my\project` or from the cygwin-point-of-view at `/cygdrive/c/path/to/my/project`.

Can you please fix this so I can use the version-manager with cygwin?

**Comment by wing328** [comment] 2020-10-15 13:35
Thanks for reporting the issue. Can you please try Git Bash as a workaround to see if it works for you?

https://gitforwindows.org/

**Comment by amjmhs** [comment] 2020-10-15 19:20
I tried it with git-bash and there it is working. For instance, I execute the following command
`$ npx openapi-generator-cli version-manager set 4.2.3`
and it does change the `openapitools.json` at my project-directory correctly.

**Comment by kay-schecker** [comment] 2020-10-15 19:28
Awesome, then I would close the issue.

**Comment by amjmhs** [comment] 2020-10-15 19:32
huh? why? @kay-schecker?  i am not working with git-bash... my whole working environment is at cygwin and it would be nice, if this version-manager will support this

**Comment by kay-schecker** [comment] 2020-10-15 20:27
Can you file a PR then, pls?

**Comment by amjmhs** [comment] 2020-10-16 10:09
I just switched to git-bash as suggested by @wing328 to test whether there is a fundamental problem or just cygwin that is not yet supported.

I can't provide a PR because I have no bugfix for this issue :(
It's something with the path-resolving at the version-service, but I haven't analyzed it in detail yet.

**Comment by kay-schecker** [comment] 2021-06-30 21:27
Unable to reproduce -> closed because there is a workaround

**Closed by kay-schecker** 2021-06-30 21:27 UTC
